<?php
session_start();
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/activity_logger.php';

if (!isset($_SESSION['user_id']) || !in_array($_SESSION['user_role'], ['admin', 'super_admin'])) {
    header("Location: " . BASE_URL . "/login.php");
    exit;
}

// RBAC Enforcement: Assistant Admins (Level 1) cannot perform write actions
if (($_SESSION['role_level'] ?? 1) < 2) {
    $_SESSION['error'] = 'Unauthorized action. Assistant Admins have read-only access.';
    header('Location: ' . ($_SERVER['HTTP_REFERER'] ?? BASE_URL . '/admin/dashboard.php'));
    exit;
}


if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}

verify_csrf_token($_POST['csrf_token'] ?? '');

$criticalLockFile = __DIR__ . '/../.critical_update_lock';
if (file_exists($criticalLockFile) && $_SESSION['user_role'] !== 'super_admin') {
    $_SESSION['error'] = 'Critical update lock is enabled. Password reset is temporarily disabled.';
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}
$targetUserId = (int)($_POST['user_id'] ?? 0);
if ($targetUserId <= 0) {
    $_SESSION['error'] = 'Invalid user selected.';
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}

$stmt = $pdo->prepare("SELECT id, name, email, role, COALESCE(role_level, 0) AS role_level FROM users WHERE id = ?");
$stmt->execute([$targetUserId]);
$target = $stmt->fetch();

if (!$target) {
    $_SESSION['error'] = 'User not found.';
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}

if ((int)$target['role_level'] >= 3 && $_SESSION['user_role'] !== 'super_admin') {
    $_SESSION['error'] = 'Protected account password cannot be reset by this role.';
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}

function generate_temp_password(): string
{
    $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
    $password = 'Sh!';
    for ($i = 0; $i < 9; $i++) {
        $password .= $alphabet[random_int(0, strlen($alphabet) - 1)];
    }
    return $password;
}
$tempPassword = generate_temp_password();
$newHash = password_hash($tempPassword, PASSWORD_DEFAULT);

$upd = $pdo->prepare("UPDATE users SET password_hash = ? WHERE id = ?");
$ok = $upd->execute([$newHash, $targetUserId]);

if (!$ok) {
    $_SESSION['error'] = 'Failed to reset password.';
    header("Location: " . BASE_URL . "/admin/password_resets.php");
    exit;
}

log_admin_activity(
    $pdo,
    $_SESSION['user_id'],
    'Admin password reset',
    'update',
    'users',
    $targetUserId,
    $target['email'],
    'Temporary password generated by admin for user account recovery'
);

$_SESSION['success'] = 'Temporary password for ' . $target['email'] . ': ' . $tempPassword . ' (share securely, then ask user to change it).';
header("Location: " . BASE_URL . "/admin/password_resets.php");
exit;
